### PR TITLE
added citations

### PR DESCRIPTION
**Pull request by mclark58**
Added citations in PLOS format, increased patch number by 1, and created RELEASE_NOTES.md file

### CODE REVIEW

**Review by samseaver — CHANGES_REQUESTED** [review]
This is minor, but papers are typically sorted in reverse chronological order can you put the "Plant J." paper first? Thanks.

**Comment by mclark58** [comment]
Sure! I was just listing them alphabetically, but that's an easy fix. Just a minute

**Comment by mclark58** [comment]
@samseaver, all done!

**Comment by samseaver** [comment]
Thanks!

**Pull request merged**
